//! Schema drift detection — fail if committed JSON Schema files
//! diverge from the schemas generated by the current Rust types.
//!
//! If this test fails, run `just schemas` to regenerate the files.

use std::path::PathBuf;

use forgeclaw_ipc::{ContainerToHost, HostToContainer};

fn schemas_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("schemas")
}

fn assert_schema_current<T: schemars::JsonSchema>(filename: &str) {
    let schema = schemars::schema_for!(T);
    let expected = serde_json::to_string_pretty(&schema).expect("serialize schema");
    let expected = format!("{expected}\n");

    let path = schemas_dir().join(filename);
    let committed = std::fs::read_to_string(&path)
        .expect("could not read committed schema — run `just schemas` to generate it");

    assert_eq!(
        committed, expected,
        "\nCommitted schema `{filename}` is out of date.\n\
         Run `just schemas` to regenerate.\n"
    );
}

#[test]
fn container_to_host_schema_is_current() {
    assert_schema_current::<ContainerToHost>("container_to_host.schema.json");
}

#[test]
fn host_to_container_schema_is_current() {
    assert_schema_current::<HostToContainer>("host_to_container.schema.json");
}
